spring:
  application:
    name: helloboot-discovery
server:
  port: 8080
calculator:
  ribbon:
    eureka:
      enabled: false
    client:
      enabled: true
    ServerListRefreshInterval: 5000